# LDA-RDP
## Linear Discriminant Analysis on Ribosomal Database Project

* https://machinelearningmastery.com/linear-discriminant-analysis-with-python/
* https://rdp.cme.msu.edu/misc/resources.jsp
* https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html

In [6]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

## Create Data

In [7]:
# create the lda model
model = LinearDiscriminantAnalysis()

In [8]:
# test classification dataset
from sklearn.datasets import make_classification
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=10, n_redundant=0, random_state=1)
# summarize the dataset
print(X.shape, y.shape)

(1000, 10) (1000,)


In [9]:
X

array([[ 0.12777556, -3.64400522, -2.23268854, ...,  2.35822076,
         1.01001752,  0.56768485],
       [ 1.29876818,  0.64951908, -0.15072343, ..., -2.55702618,
        -0.16273873,  0.68452078],
       [-1.72160156, -2.32154245,  1.46578391, ...,  0.97429449,
         2.58320993,  0.93096172],
       ...,
       [-2.42672264,  1.31447704,  1.56499359, ...,  0.28060045,
        -3.86182249,  1.81144529],
       [ 0.44874354,  2.1493849 ,  4.6952521 , ..., -3.92935458,
        -1.55384547, -1.91727757],
       [-1.95179688, -1.26917911,  2.15182832, ..., -0.71185711,
        -1.39975812,  0.17661328]])

In [10]:
type(X)

numpy.ndarray

In [8]:
X[0]

array([ 0.12777556, -3.64400522, -2.23268854, -1.82114386,  1.75466361,
        0.1243966 ,  1.03397657,  2.35822076,  1.01001752,  0.56768485])

In [7]:
y

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,

In [9]:
y[0]

0

In [5]:
# evaluate a lda model on the dataset
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=10, n_redundant=0, random_state=1)
# define model
model = LinearDiscriminantAnalysis()
# define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# summarize result
print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Mean Accuracy: 0.893 (0.033)


In [10]:
# make a prediction with a lda model on the dataset
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=10, n_redundant=0, random_state=1)
# define model
model = LinearDiscriminantAnalysis()
# fit model
model.fit(X, y)
# define new data
row = [0.12777556,-3.64400522,-2.23268854,-1.82114386,1.75466361,0.1243966,1.03397657,2.35822076,1.01001752,0.56768485]
# make a prediction
yhat = model.predict([row])
# summarize prediction
print('Predicted Class: %d' % yhat)

Predicted Class: 1


In [18]:
row = [-2.0,-3,-2,-1,1,0,1,2,1,0]
# make a prediction
yhat = model.predict([row])
# summarize prediction
print('Predicted Class: %d' % yhat)

Predicted Class: 0


## RDP Data

In [1]:
from bioinformatics import na_read
from bioinformatics import KmerVectors as kvec
from bioinformatics import NCBIDataset as nds
from bioinformatics import FASTADataset as fads

In [2]:
RDP_PATH="../data/bioinformatics/rdp/202208/"

archaea_file = RDP_PATH + "current_Archaea_unaligned.fa"
bacteria_file = RDP_PATH + "current_Bacteria_unaligned.fa"
fungi_file = RDP_PATH + "current_Fungi_unaligned.fa"

In [3]:
archaea_fads = fads.FASTADataset('archaea', archaea_file, limit=0)
print(f'archaea: [{len(archaea_fads.fasta_dataset)}]')
#archaea.fasta_dataset
bacteria_fads = fads.FASTADataset('bacteria', bacteria_file, limit=0)
print(f'bacteria: [{len(bacteria_fads.fasta_dataset)}]')

archaea: [160767]
bacteria: [3196041]


In [4]:
#kv = kvec.KmerVectors(['A','G','C','T'], 8, fastadatasets=[archaea_fads, fungi_fads])
kv = kvec.KmerVectors(['A','G','C','T'], 8, fastadatasets=[archaea_fads, bacteria_fads])
#kv = kvec.KmerVectors(['A','G','C','T'], 8, fastadatasets=[random1_fads, random2_fads])
print(kv.labels)

KmerVectors Object -
alphabet [['A', 'G', 'C', 'T']]
dict: [['AAAAAAAA', 'AAAAAAAG', 'AAAAAAAC', 'AAAAAAAT']]...[['TTTTTTTA', 'TTTTTTTG', 'TTTTTTTC', 'TTTTTTTT']]
Labels: [{'archaea': 1, 'bacteria': 2}]
[archaea]
[../data/bioinformatics/rdp/202208/current_Archaea_unaligned.fa]
[bacteria]
[../data/bioinformatics/rdp/202208/current_Bacteria_unaligned.fa]
{'archaea': 1, 'bacteria': 2}


In [5]:
d = kv.seq2KmerSentences(base_count_max=4, length_min=1400, dataset_limit=1000)

FASTA Dataset
fasta dataset: [archaea]
100020003000400050006000700080009000100001100012000capped at [1000]
-
Total:                [12346]
Using :               [1001]
skip_count_minlength: [1202]
skip_count_alphabet: [10144]
fasta dataset: [bacteria]
10002000300040005000600070008000capped at [1000]
-
Total:                [8509]
Using :               [1001]
skip_count_minlength: [1295]
skip_count_alphabet: [6214]


In [6]:
e = kv.seq2KmerEncodedNumpyVectors(base_count_max=4, length_min=1400, dataset_limit=10000)

FASTA Dataset
fasta dataset: [archaea], limit: [10000]
100020003000400050006000700080009000100001100012000130001400015000160001700018000190002000021000220002300024000250002600027000280002900030000310003200033000340003500036000370003800039000400004100042000430004400045000460004700048000490005000051000520005300054000550005600057000580005900060000610006200063000640006500066000670006800069000700007100072000730007400075000760007700078000790008000081000820008300084000850008600087000880008900090000910009200093000940009500096000970009800099000100000101000102000103000104000105000106000107000108000109000110000111000112000113000114000115000116000117000118000119000120000121000122000123000124000125000126000127000128000129000130000131000132000133000134000135000136000137000138000139000140000141000142000143000144000145000146000147000148000149000150000151000152000153000154000155000156000157000158000capped at [10000]
-
Total:             [158350]
Using :               [10001]
skip_count_minlength: [1198

In [7]:
X=e[0]
X

array([[11927, 47711, 59773, ..., 29787, 53615, 17854],
       [43309, 42166, 37595, ..., 38610, 23369, 27940],
       [11927, 47711, 59773, ..., 17757,  5492, 21969],
       ...,
       [18697,  9254, 37019, ..., 49835,  2735, 10941],
       [ 4605, 18420,  8147, ..., 49706,  2217,  8868],
       [15431, 61727, 50303, ...,  7772, 31088, 58818]])

In [8]:
y=e[1]
y

array([1, 1, 1, ..., 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
print(f'X_train len: [{len(X_train)}]')
print(f'y_train len: [{len(y_train)}]')

print(f'X_test len: [{len(X_test)}]')
print(f'y_test len: [{len(y_test)}]')

X_train len: [13400]
y_train len: [13400]
X_test len: [6600]
y_test len: [6600]


In [11]:
# make a prediction with a lda model on the dataset
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# define dataset
#X, y = make_classification(n_samples=1000, n_features=10, n_informative=10, n_redundant=0, random_state=1)
# define model
model = LinearDiscriminantAnalysis()
# fit model
model.fit(X_train, y_train)
# define new data
#row = [0.12777556,-3.64400522,-2.23268854,-1.82114386,1.75466361,0.1243966,1.03397657,2.35822076,1.01001752,0.56768485]
row = X[12]
# make a prediction
yhat = model.predict([row])
# summarize prediction
print('Predicted Class: %d' % yhat)

Predicted Class: 1


In [12]:
row = X[500]
# make a prediction
yhat = model.predict([row])
# summarize prediction
print('Predicted Class: %d' % yhat)

Predicted Class: 1


In [13]:
model.score(X_test, y_test)

0.9968181818181818